apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore2
  description: Petstore2
  annotations:
    jira/project-key: SH
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
    - streetlights
    - hello-world
